// Generated by the WOLips Templateengine Plug-in at Apr 23, 2014 3:28:12 PM
package org.boat.ui;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}

	public String hello = "TreasureBoat";
}
