// Generated by the WOLips Templateengine Plug-in at Apr 23, 2014 3:28:12 PM
package org.boat;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
